### ISSUE TITLE
vfork() usage needs to be fixed

### ISSUE THREAD

**Issue by DerDakon** [kp-org/eQmail#3]
See [my fix](https://github.com/DerDakon/qmail/commit/3021ce03832b1e744bf1184b6169b4c2ff6b678d) in [my qmail repository](https://github.com/DerDakon/qmail/).

**Comment by kp-org** [comment]
Thanks for pointing this out. I will consider this in 1.10.

**Comment by kp-org** [comment]
Done, commit 1.10-Rev.20160608. Needs a bit further testing.
